/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CatPetPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// settings.ts
var DEFAULT_SETTINGS = {
  enabled: true,
  maxPets: 5,
  showStats: false,
  defaultPetType: "cat",
  defaultPetVariant: "tabby1"
};

// src/storage/pet-storage.ts
var import_obsidian = require("obsidian");
var PetStorage = class {
  constructor(app) {
    this.app = app;
    this.basePath = "workspace/pets";
  }
  async loadPets() {
    try {
      const petsFilePath = (0, import_obsidian.normalizePath)(`${this.basePath}/pets.json`);
      const petsFile = this.app.vault.getAbstractFileByPath(petsFilePath);
      if (petsFile && petsFile instanceof import_obsidian.TFile) {
        const content = await this.app.vault.read(petsFile);
        const data = JSON.parse(content);
        return data.pets || [];
      }
      return [];
    } catch (error) {
      console.error("Failed to load pets:", error);
      return [];
    }
  }
  async savePets(pets) {
    try {
      await this.ensureDirectory();
      const filePath = (0, import_obsidian.normalizePath)(`${this.basePath}/pets.json`);
      const data = {
        version: "3.0",
        pets
      };
      const content = JSON.stringify(data, null, 2);
      const file = this.app.vault.getAbstractFileByPath(filePath);
      if (file && file instanceof import_obsidian.TFile) {
        await this.app.vault.modify(file, content);
      } else {
        await this.app.vault.create(filePath, content);
      }
    } catch (error) {
      console.error("Failed to save pets:", error);
      throw error;
    }
  }
  async ensureDirectory() {
    const exists = await this.app.vault.adapter.exists(this.basePath);
    if (!exists) {
      await this.app.vault.createFolder(this.basePath);
    }
  }
};

// src/ui/pet-container.ts
var import_obsidian3 = require("obsidian");

// src/utils/random.ts
function randomFloat(min, max) {
  return Math.random() * (max - min) + min;
}
function generateUUID() {
  return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, function(c) {
    const r = Math.random() * 16 | 0;
    const v = c === "x" ? r : r & 3 | 8;
    return v.toString(16);
  });
}

// src/models/pet.ts
var PET_TYPES = [
  {
    id: "cat",
    name: "\u732B\u54AA",
    variants: [
      { id: "tabby1", name: "\u864E\u65911", spritePath: "cat/tabby1.png", fallbackColor: "#FFA05C" },
      { id: "tabby2", name: "\u864E\u65912", spritePath: "cat/tabby2.png", fallbackColor: "#D4A574" },
      { id: "black", name: "\u9ED1\u8272", spritePath: "cat/black.png", fallbackColor: "#303030" },
      { id: "white", name: "\u767D\u8272", spritePath: "cat/white.png", fallbackColor: "#F5F5F5" },
      { id: "calico", name: "\u4E09\u8272", spritePath: "cat/calico.png", fallbackColor: "#E8C547" },
      { id: "cream", name: "\u5976\u6CB9\u8272", spritePath: "cat/cream.png", fallbackColor: "#FFF8DC" },
      { id: "creamtabby", name: "\u5976\u6CB9\u864E\u6591", spritePath: "cat/creamtabby.png", fallbackColor: "#F5DEB3" },
      { id: "grey1", name: "\u7070\u82721", spritePath: "cat/grey1.png", fallbackColor: "#A0A0A0" },
      { id: "grey2", name: "\u7070\u82722", spritePath: "cat/grey2.png", fallbackColor: "#808080" },
      { id: "grey3", name: "\u7070\u82723", spritePath: "cat/grey3.png", fallbackColor: "#696969" }
    ]
  }
];
function getPetTypeConfig(typeId) {
  return PET_TYPES.find((t) => t.id === typeId);
}
function getPetVariantConfig(typeId, variantId) {
  const type = getPetTypeConfig(typeId);
  return type == null ? void 0 : type.variants.find((v) => v.id === variantId);
}
function getVariantDisplayName(typeId, variantId) {
  const variant = getPetVariantConfig(typeId, variantId);
  return (variant == null ? void 0 : variant.name) || variantId;
}
function getVariantSpritePath(typeId, variantId) {
  const variant = getPetVariantConfig(typeId, variantId);
  return variant == null ? void 0 : variant.spritePath;
}
function getPetTypeOptions() {
  return PET_TYPES.map((type) => ({
    value: type.id,
    label: type.name
  }));
}
function getPetVariantOptions(typeId) {
  const type = getPetTypeConfig(typeId);
  if (!type)
    return [];
  return type.variants.map((variant) => ({
    value: variant.id,
    label: variant.name
  }));
}
var NAME_PREFIXES = ["\u5C0F", "\u5927", "\u80D6", "\u840C", "\u5446\u5446", "\u8C03\u76AE", "\u61D2\u61D2", "\u4E56\u4E56", "\u54AA\u54AA", "\u82B1\u82B1"];
var NAME_SUFFIXES = ["\u732B", "\u55B5", "\u54AA", "\u7403", "\u56E2\u5B50", "\u8C46\u8C46", "\u7403\u7403", "\u6BDB\u6BDB"];
function generateRandomPersonality() {
  return {
    activity: randomFloat(0.3, 0.9),
    sociability: randomFloat(0.3, 0.9)
  };
}
function generatePetName() {
  const prefix = NAME_PREFIXES[Math.floor(Math.random() * NAME_PREFIXES.length)];
  const suffix = NAME_SUFFIXES[Math.floor(Math.random() * NAME_SUFFIXES.length)];
  return prefix + suffix;
}
function createPet(name, type, variant, color) {
  var _a;
  const petType = type || "cat";
  const typeConfig = getPetTypeConfig(petType);
  const petVariant = variant || ((_a = typeConfig == null ? void 0 : typeConfig.variants[Math.floor(Math.random() * ((typeConfig == null ? void 0 : typeConfig.variants.length) || 1))]) == null ? void 0 : _a.id) || "tabby1";
  const variantConfig = getPetVariantConfig(petType, petVariant);
  const fallbackColor = color || (variantConfig == null ? void 0 : variantConfig.fallbackColor) || "#FFA05C";
  return {
    id: generateUUID(),
    name: name || generatePetName(),
    type: petType,
    variant: petVariant,
    color: fallbackColor,
    personality: generateRandomPersonality(),
    state: { type: "idle", since: Date.now() },
    position: {
      x: Math.floor(randomFloat(100, (window == null ? void 0 : window.innerWidth) ? window.innerWidth - 228 : 500)),
      direction: Math.random() > 0.5 ? "right" : "left"
    },
    createdAt: new Date().toISOString()
  };
}
function getPetFullDescription(pet) {
  var _a;
  const typeName = ((_a = getPetTypeConfig(pet.type)) == null ? void 0 : _a.name) || pet.type;
  const variantName = getVariantDisplayName(pet.type, pet.variant);
  return `${typeName} \xB7 ${variantName}`;
}

// src/renderer/sprite-animation.ts
var ANIMATION_CONFIG = {
  // 第0行 (sy=0): 
  // 列0: Idle标签, 列1: Idle帧1, 列2: Stand标签(!), 列3: Idle帧2, 列4: ?, 列5-8: Stand帧
  idle: { row: 0, startCol: 1, frames: 2 },
  // 帧在列1和列3（跳过列2的Stand标签！）
  stand: { row: 0, startCol: 5, frames: 4 },
  // 列5,6,7,8
  // 第1行 (sy=32): Blink(列1-2) + Jump(列3-4)
  // 列0=Blink标签, 列1-2=Blink帧, 列3-4=Jump帧, 列5可能是另一个标签
  blink: { row: 1, startCol: 1, frames: 2 },
  jump: { row: 1, startCol: 3, frames: 2 },
  // 第2行 (sy=64): Walk + Run
  walk: { row: 2, startCol: 1, frames: 3 },
  run: { row: 2, startCol: 6, frames: 2 },
  // 第3行 (sy=96): Eat + Inspect
  eat: { row: 3, startCol: 1, frames: 3 },
  inspect: { row: 3, startCol: 5, frames: 4 },
  // 第4行 (sy=128): Swim
  swim: { row: 4, startCol: 1, frames: 5 },
  // 第5行 (sy=160): Sound(列1-3) + Sleep(列6，只有1帧！)
  // 列5是Sleep标签(黑)，列6是Sleep帧，列7-8是黑的
  sound: { row: 5, startCol: 1, frames: 3 },
  sleep: { row: 5, startCol: 6, frames: 1 },
  fall: { row: 1, startCol: 5, frames: 2 }
};
var ACTION_SETTINGS = {
  idle: { fps: 2, loop: true },
  // 发呆：缓慢呼吸
  stand: { fps: 2, loop: true },
  // 站立：缓慢
  blink: { fps: 8, loop: false },
  // 眨眼：快速
  jump: { fps: 8, loop: false },
  // 跳跃：快速
  walk: { fps: 6, loop: true },
  // 行走：与移动速度协调 (~6fps = 每帧移动10px)
  run: { fps: 10, loop: true },
  // 奔跑：更快
  eat: { fps: 4, loop: true },
  // 进食
  inspect: { fps: 4, loop: true },
  // 观察
  swim: { fps: 6, loop: true },
  // 游泳
  sound: { fps: 6, loop: false },
  // 发声
  sleep: { fps: 1, loop: true },
  // 睡觉：非常缓慢
  fall: { fps: 8, loop: false }
  // 下落
};
var SpriteAnimation = class {
  constructor(imageSrc) {
    this.loaded = false;
    this.frameWidth = 32;
    this.frameHeight = 32;
    this.image = new Image();
    this.image.onload = () => {
      var _a;
      this.loaded = true;
      (_a = this.onLoadCallback) == null ? void 0 : _a.call(this);
    };
    this.image.onerror = (err) => {
      console.error("[SpriteAnimation] \u56FE\u7247\u52A0\u8F7D\u5931\u8D25:", imageSrc, err);
    };
    this.image.src = imageSrc;
    this.currentState = {
      action: "idle",
      frame: 0,
      lastFrameTime: Date.now()
    };
  }
  onLoad(callback) {
    if (this.loaded) {
      callback();
    } else {
      this.onLoadCallback = callback;
    }
  }
  isLoaded() {
    return this.loaded;
  }
  getCurrentAction() {
    return this.currentState.action;
  }
  setAction(action) {
    if (this.currentState.action === action)
      return;
    const cfg = ANIMATION_CONFIG[action];
    if (!cfg) {
      console.warn(`[SpriteAnimation] \u52A8\u4F5C "${action}" \u4E0D\u5B58\u5728`);
      return;
    }
    this.currentState = {
      action,
      frame: 0,
      lastFrameTime: Date.now()
    };
  }
  update() {
    if (!this.loaded)
      return;
    const settings = ACTION_SETTINGS[this.currentState.action];
    if (!settings)
      return;
    const now = Date.now();
    const frameInterval = 1e3 / settings.fps;
    if (now - this.currentState.lastFrameTime >= frameInterval) {
      const cfg = ANIMATION_CONFIG[this.currentState.action];
      if (!cfg)
        return;
      const maxFrames = cfg.frames;
      if (maxFrames <= 1) {
        this.currentState.frame = 0;
      } else if (settings.loop) {
        this.currentState.frame = (this.currentState.frame + 1) % maxFrames;
      } else {
        this.currentState.frame = Math.min(this.currentState.frame + 1, maxFrames - 1);
      }
      this.currentState.lastFrameTime = now;
    }
  }
  render(ctx, x, y, scale = 1) {
    if (!this.loaded)
      return;
    const { sx, sy } = this.getFramePosition();
    const action = this.currentState.action;
    const frame = this.currentState.frame;
    if (sy === 0 && (sx === 0 || sx === 64 || sx === 128)) {
      return;
    }
    ctx.drawImage(
      this.image,
      sx,
      sy,
      this.frameWidth,
      this.frameHeight,
      x - this.frameWidth * scale / 2,
      y - this.frameHeight * scale / 2,
      this.frameWidth * scale,
      this.frameHeight * scale
    );
  }
  getFramePosition() {
    const action = this.currentState.action;
    const frame = this.currentState.frame;
    const cfg = ANIMATION_CONFIG[action];
    if (!cfg) {
      return { sx: 32, sy: 0 };
    }
    const safeFrame = Math.max(0, Math.min(frame, cfg.frames - 1));
    let col;
    if (action === "idle") {
      col = safeFrame === 0 ? 1 : 3;
    } else {
      col = cfg.startCol + safeFrame;
    }
    const sx = col * this.frameWidth;
    const sy = cfg.row * this.frameHeight;
    return { sx, sy };
  }
};

// src/renderer/pet-renderer.ts
var PetRenderer = class {
  constructor(app, container, basePath = ".obsidian/plugins/obsidian-cat-pet") {
    this.sprite = null;
    this.currentPetType = "";
    this.currentPetVariant = "";
    this.scale = 2;
    this.app = app;
    this.container = container;
    this.basePath = basePath;
    this.canvas = document.createElement("canvas");
    this.canvas.width = 64;
    this.canvas.height = 96;
    this.canvas.className = "pet-canvas";
    this.container.appendChild(this.canvas);
    const ctx = this.canvas.getContext("2d");
    if (!ctx) {
      throw new Error("Failed to get canvas context");
    }
    this.ctx = ctx;
    this.ctx.imageSmoothingEnabled = false;
  }
  async setPetSprite(pet) {
    if (this.currentPetType === pet.type && this.currentPetVariant === pet.variant && this.sprite) {
      return;
    }
    this.currentPetType = pet.type || "cat";
    this.currentPetVariant = pet.variant || "tabby1";
    const spritePath = getVariantSpritePath(pet.type, pet.variant);
    if (!spritePath) {
      console.warn(`[PetRenderer] \u672A\u627E\u5230\u7CBE\u7075\u56FE\u8DEF\u5F84: ${pet.type}/${pet.variant}`);
      this.sprite = null;
      return;
    }
    const fullPath = this.getAssetUrl(spritePath);
    this.sprite = new SpriteAnimation(fullPath);
    return new Promise((resolve) => {
      var _a;
      (_a = this.sprite) == null ? void 0 : _a.onLoad(() => {
        resolve();
      });
      setTimeout(() => resolve(), 3e3);
    });
  }
  getAssetUrl(path) {
    const pluginPath = `${this.basePath}/assets/pets/${path}`;
    try {
      const resourcePath = this.app.vault.adapter.getResourcePath(pluginPath);
      return resourcePath;
    } catch (e) {
      return pluginPath;
    }
  }
  render(pet) {
    if (!this.sprite || this.currentPetType !== pet.type || this.currentPetVariant !== pet.variant) {
      this.setPetSprite(pet);
    }
    this.ctx.clearRect(0, 0, this.canvas.width, this.canvas.height);
    if (!this.sprite || !this.sprite.isLoaded()) {
      this.drawLoadingPlaceholder(pet);
      return;
    }
    this.updateAnimationState(pet);
    this.sprite.update();
    this.ctx.save();
    if (pet.position.direction === "left") {
      this.ctx.translate(this.canvas.width, 0);
      this.ctx.scale(-1, 1);
    }
    const centerX = this.canvas.width / 2;
    let centerY = this.canvas.height - 32;
    if (pet.state.type === "jump") {
      const elapsed = Date.now() - pet.state.since;
      const jumpDuration = 250;
      const progress = Math.min(elapsed / jumpDuration, 1);
      const jumpHeight = 20;
      const offset = Math.sin(progress * Math.PI) * jumpHeight;
      centerY -= offset;
    }
    this.sprite.render(this.ctx, centerX, centerY, this.scale);
    this.ctx.restore();
  }
  updateAnimationState(pet) {
    if (!this.sprite)
      return;
    const actionMap = {
      idle: "idle",
      walk: "walk",
      sleep: "sleep",
      petted: "blink",
      jump: "jump"
    };
    const targetAction = actionMap[pet.state.type] || "idle";
    this.sprite.setAction(targetAction);
  }
  // 播放跳跃动画
  playJump() {
    if (!this.sprite)
      return;
    this.sprite.setAction("jump");
  }
  drawLoadingPlaceholder(pet) {
    const centerX = this.canvas.width / 2;
    const centerY = this.canvas.height / 2;
    this.ctx.save();
    this.ctx.fillStyle = pet.color || "#FFA05C";
    this.ctx.beginPath();
    this.ctx.arc(centerX, centerY, 16, 0, Math.PI * 2);
    this.ctx.fill();
    this.ctx.fillStyle = "#fff";
    this.ctx.font = "10px sans-serif";
    this.ctx.textAlign = "center";
    this.ctx.fillText("...", centerX, centerY + 4);
    this.ctx.restore();
  }
  getCanvas() {
    return this.canvas;
  }
  destroy() {
    this.canvas.remove();
  }
};

// src/ui/chat-bubble.ts
var import_obsidian2 = require("obsidian");
var ChatBubbleModal = class extends import_obsidian2.Modal {
  constructor(app, pet) {
    super(app);
    this.messages = [];
    this.isLoading = false;
    this.aiPlugin = null;
    this.pet = pet;
    this.findAIPlugin();
  }
  /**
   * 查找可用的 AI 插件
   */
  findAIPlugin() {
    const plugins = this.app.plugins.plugins;
    if (plugins["agent-window-in-obsidian"]) {
      this.aiPlugin = plugins["agent-window-in-obsidian"];
      console.log("[PetChat] Found AI plugin: agent-window-in-obsidian");
      return;
    }
    if (plugins["claudian"]) {
      this.aiPlugin = plugins["claudian"];
      console.log("[PetChat] Found AI plugin: claudian");
      return;
    }
    console.log("[PetChat] No AI plugin found");
  }
  /**
   * 检查是否有 AI 可用
   */
  hasAI() {
    return this.aiPlugin !== null && this.aiPlugin.embeddedChatService !== null;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("pet-chat-modal", "pi-chat-modal");
    const header = contentEl.createDiv("chat-modal-header pi-chat-header");
    header.createEl("span", { text: `\u{1F431} ${this.pet.name}`, cls: "chat-modal-title pi-chat-title" });
    const btnGroup = header.createDiv("chat-modal-btns pi-chat-btns");
    const convertBtn = btnGroup.createEl("button", {
      text: "\u{1F4DD} \u8F6C\u5361\u7247",
      cls: "chat-modal-convert-btn pi-chat-convert-btn"
    });
    convertBtn.addEventListener("click", () => this.convertToCard());
    this.messagesContainer = contentEl.createDiv("chat-modal-messages pi-chat-messages");
    if (this.hasAI()) {
      this.addMessage("cat", `\u55B5~ \u6211\u662F ${this.pet.name}\uFF0C\u6211\u662F\u667A\u80FD\u732B\u54AA\uFF0C\u53EF\u4EE5\u56DE\u7B54\u4F60\u7684\u95EE\u9898\u54E6\uFF01`);
    } else {
      this.addMessage("cat", `\u55B5~ \u6211\u662F ${this.pet.name}\uFF0C\u6765\u627E\u6211\u804A\u5929\u5427\uFF01\uFF08\u63D0\u793A\uFF1A\u5B89\u88C5 AgentWindowInObsidian \u63D2\u4EF6\u53EF\u542F\u7528AI\uFF09`);
    }
    const inputArea = contentEl.createDiv("chat-modal-input-area pi-chat-input-area");
    this.inputEl = inputArea.createEl("input", {
      type: "text",
      placeholder: this.hasAI() ? "\u95EE\u70B9\u4EC0\u4E48..." : "\u548C\u732B\u54AA\u8BF4\u8BF4\u8BDD...",
      cls: "chat-modal-input pi-chat-input"
    });
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !this.isLoading) {
        this.sendMessage();
      }
    });
    const sendBtn = inputArea.createEl("button", {
      text: "\u53D1\u9001",
      cls: "chat-modal-send pi-chat-send"
    });
    sendBtn.addEventListener("click", () => {
      if (!this.isLoading) {
        this.sendMessage();
      }
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
  /**
   * 发送消息
   */
  async sendMessage() {
    const content = this.inputEl.value.trim();
    if (!content || this.isLoading)
      return;
    this.addMessage("user", content);
    this.inputEl.value = "";
    this.isLoading = true;
    const loadingEl = this.showLoading();
    try {
      let reply;
      if (this.hasAI()) {
        reply = await this.getAIReply(content);
      } else {
        await this.delay(500);
        reply = this.generateLocalReply(content);
      }
      loadingEl.remove();
      this.addMessage("cat", reply);
    } catch (error) {
      console.error("[PetChat] Error:", error);
      loadingEl.remove();
      this.addMessage("cat", "\u55B5\u545C... \u6211\u597D\u50CF\u6709\u70B9\u56F0\u4E86\uFF0C\u7A0D\u540E\u518D\u804A\u597D\u5417\uFF1F");
    } finally {
      this.isLoading = false;
    }
  }
  /**
   * 获取 AI 回复
   */
  async getAIReply(userContent) {
    try {
      const history = this.messages.map((m) => ({
        role: m.role === "user" ? "user" : "assistant",
        content: m.content
      }));
      console.log("[PetChat] Sending to AI:", history);
      const response = await this.aiPlugin.embeddedChatService.chat(history);
      console.log("[PetChat] AI response:", response);
      if (response && response.startsWith("[")) {
        console.warn("[PetChat] AI returned error, using local reply");
        return this.generateLocalReply(userContent);
      }
      return response || this.generateLocalReply(userContent);
    } catch (error) {
      console.error("[PetChat] AI call failed:", error);
      return this.generateLocalReply(userContent);
    }
  }
  /**
   * 延迟
   */
  delay(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }
  /**
   * 显示加载中
   */
  showLoading() {
    const loading = this.messagesContainer.createDiv("chat-modal-message pi-chat-message cat loading");
    loading.innerHTML = `
			<div class="chat-modal-avatar pi-chat-avatar">\u{1F431}</div>
			<div class="chat-modal-content pi-chat-content">
				<span class="loading-dots">\u601D\u8003\u4E2D<span>.</span><span>.</span><span>.</span></span>
			</div>
		`;
    this.messagesContainer.scrollTop = this.messagesContainer.scrollHeight;
    return loading;
  }
  /**
   * 添加消息到界面
   */
  addMessage(role, content) {
    const message = {
      role,
      content,
      timestamp: Date.now()
    };
    this.messages.push(message);
    const msgEl = this.messagesContainer.createDiv(`chat-modal-message pi-chat-message ${role}`);
    const avatar = msgEl.createDiv("chat-modal-avatar pi-chat-avatar");
    avatar.textContent = role === "user" ? "\u{1F60A}" : "\u{1F431}";
    const contentEl = msgEl.createDiv("chat-modal-content pi-chat-content");
    contentEl.textContent = content;
    this.messagesContainer.scrollTop = this.messagesContainer.scrollHeight;
  }
  /**
   * 本地预设回复（作为降级方案）
   */
  generateLocalReply(userContent) {
    const lowerContent = userContent.toLowerCase();
    if (lowerContent.includes("\u4F60\u597D") || lowerContent.includes("\u55E8")) {
      return "\u55B5~ \u4F60\u597D\u5440\uFF01\u4ECA\u5929\u8FC7\u5F97\u600E\u4E48\u6837\uFF1F";
    }
    if (lowerContent.includes("\u540D\u5B57")) {
      return `\u6211\u53EB ${this.pet.name}\uFF0C\u5F88\u9AD8\u5174\u8BA4\u8BC6\u4F60\uFF01`;
    }
    if (lowerContent.includes("\u5403") || lowerContent.includes("\u997F")) {
      return "\u6211\u662F\u4E00\u53EA\u6570\u5B57\u732B\u54AA\uFF0C\u4E0D\u9700\u8981\u5403\u4E1C\u897F~ \u4F46\u6211\u559C\u6B22\u5403\u865A\u62DF\u7684\u5C0F\u9C7C\u5E72\uFF01\u{1F41F}";
    }
    if (lowerContent.includes("\u7761") || lowerContent.includes("\u56F0")) {
      return "\u732B\u54AA\u786E\u5B9E\u5F88\u559C\u6B22\u7761\u89C9\uFF0C\u4E00\u5929\u8981\u776116\u4E2A\u5C0F\u65F6\u5462\uFF01\u{1F634}";
    }
    if (lowerContent.includes("\u6478") || lowerContent.includes("\u4E56")) {
      return "\u55B5\u545C~ \u8C22\u8C22\u4F60\u5938\u6211\uFF01\u6211\u5F88\u4E56\u7684~ \u{1F495}";
    }
    if (lowerContent.includes("\u7B14\u8BB0") || lowerContent.includes("\u5199")) {
      return "\u4F60\u5728\u5199\u7B14\u8BB0\u5417\uFF1F\u70B9\u51FB\u300C\u8F6C\u5361\u7247\u300D\u53EF\u4EE5\u4FDD\u5B58\u6211\u4EEC\u7684\u5BF9\u8BDD\u54E6\uFF01";
    }
    if (lowerContent.includes("\u62DC\u62DC") || lowerContent.includes("\u518D\u89C1")) {
      return "\u518D\u89C1~ \u8BB0\u5F97\u5E38\u6765\u627E\u6211\u73A9\u54E6\uFF01\u55B5~ \u{1F44B}";
    }
    const defaultReplies = [
      "\u55B5\uFF1F\u4F60\u5728\u8BF4\u4EC0\u4E48\u5440\uFF1F",
      "\u6211\u662F\u4E00\u53EA\u5C0F\u732B\u54AA\uFF0C\u4E0D\u592A\u61C2\u4F60\u5728\u8BF4\u4EC0\u4E48\u5462~",
      "\u55EF\u55EF\uFF0C\u6211\u5728\u542C\u5462\uFF01\u7EE7\u7EED\u8BF4~",
      "\u8FD9\u4E2A\u95EE\u9898\u597D\u96BE\u5440\uFF0C\u8BA9\u6211\u60F3\u60F3...",
      "\u55B5\u545C~ \u6211\u4EEC\u53EF\u4EE5\u804A\u70B9\u522B\u7684\u5417\uFF1F"
    ];
    return defaultReplies[Math.floor(Math.random() * defaultReplies.length)];
  }
  /**
   * 转化为卡片 - 将当前对话保存为 AgentWindowInObsidian 格式的笔记
   */
  async convertToCard() {
    var _a;
    if (this.messages.length <= 1) {
      new import_obsidian2.Notice("\u8FD8\u6CA1\u6709\u5BF9\u8BDD\u5185\u5BB9\u54E6\uFF0C\u5148\u804A\u51E0\u53E5\u5427\uFF01");
      return;
    }
    const activeFile = this.app.workspace.getActiveFile();
    const parentPath = ((_a = activeFile == null ? void 0 : activeFile.parent) == null ? void 0 : _a.path) || "";
    const timestamp = Date.now();
    const randomStr = Math.random().toString(36).substring(2, 9);
    const cardId = `card-${timestamp}-${randomStr}`;
    const now = new Date();
    const dateStr = now.toLocaleDateString("zh-CN").replace(/\//g, "-");
    const timeStr = now.toLocaleTimeString("zh-CN", { hour: "2-digit", minute: "2-digit", second: "2-digit" }).replace(/:/g, "");
    const fileName = `${this.pet.name}\u7684\u5BF9\u8BDD\u5361\u7247-${dateStr}-${timeStr}`;
    const newFilePath = parentPath ? `${parentPath}/${fileName}.md` : `${fileName}.md`;
    const dateTimeStr = now.toLocaleString("zh-CN", {
      year: "numeric",
      month: "2-digit",
      day: "2-digit",
      hour: "2-digit",
      minute: "2-digit",
      second: "2-digit"
    });
    const content = `# \u{1F431} \u4E0E ${this.pet.name} \u7684\u5BF9\u8BDD\u5361\u7247

> \u{1F4C5} \u521B\u5EFA\u65F6\u95F4\uFF1A${dateTimeStr}
> ${activeFile ? `> \u{1F517} \u6765\u6E90\u7B14\u8BB0\uFF1A[[${activeFile.basename}]]` : ""}
> \u{1F916} ${this.hasAI() ? "AI \u667A\u80FD\u5BF9\u8BDD" : "\u672C\u5730\u5BF9\u8BDD"}

---

> \u{1F4AC} \u70B9\u51FB\u4E0B\u65B9\u7684\u5BF9\u8BDD\u5361\u7247\u53EF\u4EE5\u7EE7\u7EED\u4E0E ${this.pet.name} \u804A\u5929\uFF1A

\`\`\`ai-chat
${cardId}
\`\`\`

---

*\u{1F43E} \u7531 [[\u732B\u54AA\u5BA0\u7269\u63D2\u4EF6]]\u521B\u5EFA*
`;
    try {
      const newFile = await this.app.vault.create(newFilePath, content);
      await this.saveChatHistory(cardId, parentPath);
      await this.app.workspace.openLinkText(newFile.path, "");
      new import_obsidian2.Notice(`\u{1F4DD} \u5BF9\u8BDD\u5361\u7247\u5DF2\u521B\u5EFA\uFF1A${fileName}`);
      this.close();
    } catch (error) {
      console.error("[PetChat] Failed to create card:", error);
      new import_obsidian2.Notice("\u521B\u5EFA\u5361\u7247\u5931\u8D25\uFF0C\u8BF7\u91CD\u8BD5");
    }
  }
  /**
   * 保存对话历史到 .ai-chats/ 目录（AgentWindowInObsidian 格式）
   */
  async saveChatHistory(cardId, parentPath) {
    try {
      const chatDir = parentPath ? `${parentPath}/.ai-chats` : ".ai-chats";
      const chatFilePath = `${chatDir}/${cardId}.json`;
      const now = Date.now();
      const chatData = {
        cardId,
        sessionId: `pet-${now}`,
        messages: this.messages.map((m) => ({
          role: m.role === "user" ? "user" : "assistant",
          content: m.content,
          timestamp: m.timestamp
        })),
        isActive: true,
        createdAt: now,
        updatedAt: now
      };
      const dirExists = await this.app.vault.adapter.exists(chatDir);
      if (!dirExists) {
        await this.app.vault.createFolder(chatDir);
      }
      await this.app.vault.adapter.write(chatFilePath, JSON.stringify(chatData, null, 2));
      console.log("[PetChat] Chat history saved:", chatFilePath);
    } catch (error) {
      console.error("[PetChat] Failed to save chat history:", error);
    }
  }
};
var ChatBubble = class {
  constructor(app, pet) {
    this.modal = new ChatBubbleModal(app, pet);
  }
  open() {
    this.modal.open();
  }
  close() {
    this.modal.close();
  }
};

// src/ui/pet-container.ts
var PetContainer = class {
  constructor(app, plugin) {
    this.pets = /* @__PURE__ */ new Map();
    this.visible = true;
    this.animationFrameId = null;
    this.lastActivityTime = Date.now();
    this.activeChatBubble = null;
    this.app = app;
    this.plugin = plugin;
    this.createContainer();
    this.setupActivityTracking();
    this.startAnimationLoop();
  }
  createContainer() {
    this.container = document.createElement("div");
    this.container.className = "pet-floating-container";
    document.body.appendChild(this.container);
  }
  setupActivityTracking() {
    document.addEventListener("keydown", () => {
      this.lastActivityTime = Date.now();
    });
    document.addEventListener("click", () => {
      this.lastActivityTime = Date.now();
    });
  }
  startAnimationLoop() {
    const loop = () => {
      this.updatePets();
      this.renderPets();
      this.animationFrameId = requestAnimationFrame(loop);
    };
    this.animationFrameId = requestAnimationFrame(loop);
  }
  updatePets() {
    const now = Date.now();
    const inactiveTime = now - this.lastActivityTime;
    for (const view of this.pets.values()) {
      const pet = view.pet;
      const deltaTime = now - view.lastUpdateTime;
      view.lastUpdateTime = now;
      this.updatePetBehavior(pet, deltaTime, inactiveTime);
    }
  }
  updatePetBehavior(pet, deltaTime, inactiveTime) {
    switch (pet.state.type) {
      case "idle":
        this.handleIdleState(pet, inactiveTime);
        break;
      case "walk":
        this.handleWalkState(pet, deltaTime);
        break;
      case "sleep":
        this.handleSleepState(pet);
        break;
      case "petted":
        this.handlePettedState(pet);
        break;
      case "jump":
        break;
    }
    if (inactiveTime > 10 * 60 * 1e3 && pet.state.type !== "sleep" && Math.random() < 0.3) {
      pet.state = { type: "sleep", since: Date.now() };
    }
  }
  handleIdleState(pet, inactiveTime) {
    const idleState = pet.state;
    const elapsed = Date.now() - idleState.since;
    const maxIdleTime = 3e3 / pet.personality.activity;
    if (elapsed > maxIdleTime) {
      if (Math.random() < 0.3) {
        pet.state = { type: "jump", since: Date.now() };
        setTimeout(() => {
          if (pet.state.type === "jump") {
            pet.state = { type: "idle", since: Date.now() };
          }
        }, 300);
      } else {
        const targetX = this.pickRandomTargetX(pet);
        pet.state = { type: "walk", targetX };
      }
    }
  }
  handleWalkState(pet, deltaTime) {
    const walkState = pet.state;
    const dx = walkState.targetX - pet.position.x;
    const speed = 45 * (deltaTime / 1e3);
    const moveDistance = Math.sign(dx) * Math.min(Math.abs(dx), speed);
    pet.position.x += moveDistance;
    pet.position.direction = dx > 0 ? "right" : "left";
    if (Math.abs(dx) < 1) {
      pet.state = { type: "idle", since: Date.now() };
    }
  }
  handleSleepState(pet) {
  }
  handlePettedState(pet) {
    const pettedState = pet.state;
    const elapsed = Date.now() - pettedState.since;
    if (elapsed > 2e3) {
      pet.state = { type: "idle", since: Date.now() };
    }
  }
  pickRandomTargetX(pet) {
    const margin = 100;
    const minX = margin;
    const maxX = window.innerWidth - 228;
    return Math.floor(Math.random() * (maxX - minX) + minX);
  }
  renderPets() {
    for (const view of this.pets.values()) {
      view.element.style.left = `${view.pet.position.x}px`;
      view.renderer.render(view.pet);
    }
  }
  addPet(pet) {
    if (this.pets.size >= this.plugin.settings.maxPets) {
      new import_obsidian3.Notice(`\u5BA0\u7269\u6570\u91CF\u5DF2\u8FBE\u4E0A\u9650 (${this.plugin.settings.maxPets})`);
      return;
    }
    const element = document.createElement("div");
    element.className = "pet-element";
    element.style.position = "fixed";
    element.style.left = `${pet.position.x}px`;
    element.style.bottom = "10px";
    element.style.width = "64px";
    element.style.height = "96px";
    element.style.zIndex = "1000";
    element.style.cursor = "pointer";
    element.title = `${pet.name} (${getPetFullDescription(pet)})`;
    const renderer = new PetRenderer(this.app, element);
    element.addEventListener("click", () => this.onPetClick(pet.id));
    element.addEventListener("contextmenu", (e) => {
      e.preventDefault();
      this.showContextMenu(pet.id, e);
    });
    this.setupDragFeature(pet.id, element);
    this.container.appendChild(element);
    const view = {
      pet,
      element,
      renderer,
      lastUpdateTime: Date.now()
    };
    this.pets.set(pet.id, view);
    this.plugin.storage.savePets(this.getPets());
    console.log("Added pet:", pet.name, getPetFullDescription(pet));
  }
  removePet(petId) {
    const view = this.pets.get(petId);
    if (view) {
      view.renderer.destroy();
      view.element.remove();
      this.pets.delete(petId);
    }
    this.plugin.storage.savePets(this.getPets());
  }
  getPets() {
    return Array.from(this.pets.values()).map((v) => v.pet);
  }
  createPet() {
    const pet = createPet(
      void 0,
      // 随机名字
      this.plugin.settings.defaultPetType,
      this.plugin.settings.defaultPetVariant
    );
    this.addPet(pet);
    new import_obsidian3.Notice(`\u{1F431} ${pet.name} (${getPetFullDescription(pet)}) \u6765\u4E86\uFF01`);
    return pet;
  }
  onPetClick(petId) {
    const view = this.pets.get(petId);
    if (!view)
      return;
    if (view.pet.state.type === "sleep") {
      view.pet.state = { type: "idle", since: Date.now() };
      new import_obsidian3.Notice(`${view.pet.name} \u9192\u4E86\uFF01`);
      this.plugin.storage.savePets(this.getPets());
      return;
    }
    view.pet.state = { type: "jump", since: Date.now() };
    view.renderer.playJump();
    setTimeout(() => {
      this.showHeartEffect(view);
      view.pet.state = { type: "idle", since: Date.now() };
      this.plugin.storage.savePets(this.getPets());
    }, 250);
  }
  showHeartEffect(view) {
    const heart = document.createElement("div");
    heart.className = "pet-heart-effect";
    heart.textContent = "\u2764\uFE0F";
    heart.style.position = "absolute";
    heart.style.left = "20px";
    heart.style.top = "-10px";
    heart.style.fontSize = "20px";
    heart.style.pointerEvents = "none";
    heart.style.animation = "pet-heart-float 1.5s ease-out forwards";
    view.element.appendChild(heart);
    setTimeout(() => heart.remove(), 1500);
  }
  // 设置拖动功能
  setupDragFeature(petId, element) {
    let isDragging = false;
    let startX = 0;
    let startY = 0;
    let startLeft = 0;
    let startBottom = 0;
    let dragThreshold = 5;
    const onMouseDown = (e) => {
      if (e.button !== 0)
        return;
      isDragging = false;
      startX = e.clientX;
      startY = e.clientY;
      startLeft = parseInt(element.style.left || "0");
      startBottom = parseInt(element.style.bottom || "0");
      document.addEventListener("mousemove", onMouseMove);
      document.addEventListener("mouseup", onMouseUp);
    };
    const onMouseMove = (e) => {
      const dx = e.clientX - startX;
      const dy = e.clientY - startY;
      if (Math.abs(dx) > dragThreshold || Math.abs(dy) > dragThreshold) {
        isDragging = true;
      }
      if (isDragging) {
        e.preventDefault();
        const view = this.pets.get(petId);
        if (view) {
          const newLeft = startLeft + dx;
          const newBottom = startBottom - dy;
          const maxX = window.innerWidth - 100;
          const minX = 0;
          const maxBottom = window.innerHeight - 100;
          const minBottom = 0;
          view.pet.position.x = Math.max(minX, Math.min(maxX, newLeft));
          element.style.left = `${view.pet.position.x}px`;
          element.style.bottom = `${Math.max(minBottom, Math.min(maxBottom, newBottom))}px`;
        }
      }
    };
    const onMouseUp = (e) => {
      document.removeEventListener("mousemove", onMouseMove);
      document.removeEventListener("mouseup", onMouseUp);
      if (isDragging) {
        const view = this.pets.get(petId);
        if (view) {
          view.pet.state = { type: "idle", since: Date.now() };
          this.plugin.storage.savePets(this.getPets());
        }
      }
    };
    element.addEventListener("mousedown", onMouseDown);
  }
  showContextMenu(petId, event) {
    const view = this.pets.get(petId);
    if (!view)
      return;
    const menu = new import_obsidian3.Menu();
    menu.addItem(
      (item) => item.setTitle("\u{1F4AC} \u5F00\u59CB\u5BF9\u8BDD").setIcon("message-circle").onClick(() => this.startChat(view.pet))
    );
    menu.addItem(
      (item) => item.setTitle("\u270F\uFE0F \u6539\u540D").setIcon("edit").onClick(() => this.renamePet(petId))
    );
    menu.addSeparator();
    menu.addItem(
      (item) => item.setTitle("\u{1F44B} \u9001\u8D70\u8FD9\u53EA\u5BA0\u7269").setIcon("trash").onClick(() => this.confirmRemovePet(petId))
    );
    menu.showAtPosition({ x: event.clientX, y: event.clientY });
  }
  /**
   * 开始对话 - 打开聊天气泡
   */
  startChat(pet) {
    if (this.activeChatBubble) {
      this.activeChatBubble.close();
    }
    this.activeChatBubble = new ChatBubble(this.app, pet);
    this.activeChatBubble.open();
  }
  renamePet(petId) {
    const view = this.pets.get(petId);
    if (!view)
      return;
    const newName = prompt(`\u7ED9 ${view.pet.name} \u8D77\u4E2A\u65B0\u540D\u5B57\uFF1A`, view.pet.name);
    if (newName && newName.trim() && newName.trim() !== view.pet.name) {
      view.pet.name = newName.trim();
      view.element.title = `${view.pet.name} (${getPetFullDescription(view.pet)})`;
      this.plugin.storage.savePets(this.getPets());
      new import_obsidian3.Notice(`\u5BA0\u7269\u73B0\u5728\u53EB ${view.pet.name} \u4E86\uFF01`);
    }
  }
  confirmRemovePet(petId) {
    const view = this.pets.get(petId);
    if (!view)
      return;
    if (confirm(`\u786E\u5B9A\u8981\u9001\u8D70 ${view.pet.name} \u5417\uFF1F\u8FD9\u5C06\u5220\u9664\u6240\u6709\u76F8\u5173\u6570\u636E\u3002`)) {
      this.removePet(petId);
      new import_obsidian3.Notice(`${view.pet.name} \u5DF2\u7ECF\u88AB\u9001\u8D70\u4E86...`);
    }
  }
  toggleVisibility() {
    this.visible = !this.visible;
    this.container.style.display = this.visible ? "block" : "none";
  }
  isVisible() {
    return this.visible;
  }
  destroy() {
    if (this.animationFrameId) {
      cancelAnimationFrame(this.animationFrameId);
    }
    if (this.activeChatBubble) {
      this.activeChatBubble.close();
    }
    for (const view of this.pets.values()) {
      view.renderer.destroy();
    }
    this.container.remove();
  }
};

// main.ts
var CatPetPlugin = class extends import_obsidian4.Plugin {
  async onload() {
    console.log("Loading Obsidian Pet Plugin");
    await this.loadSettings();
    this.storage = new PetStorage(this.app);
    if (this.settings.enabled) {
      this.container = new PetContainer(this.app, this);
      await this.loadPets();
    }
    this.addSettingTab(new CatPetSettingTab(this.app, this));
    this.addCommand({
      id: "create-pet",
      name: "\u65B0\u5EFA\u5BA0\u7269",
      callback: () => {
        this.createPet();
      }
    });
    this.addCommand({
      id: "toggle-visibility",
      name: "\u663E\u793A/\u9690\u85CF\u5BA0\u7269",
      callback: () => {
        this.toggleVisibility();
      }
    });
  }
  onunload() {
    console.log("Unloading Obsidian Pet Plugin");
    if (this.container) {
      this.container.destroy();
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async loadPets() {
    const pets = await this.storage.loadPets();
    if (pets.length === 0) {
      console.log('No pets found. Use "\u65B0\u5EFA\u5BA0\u7269" command to create one.');
    } else {
      for (const pet of pets) {
        this.container.addPet(pet);
      }
    }
  }
  toggleVisibility() {
    if (this.container) {
      this.container.toggleVisibility();
      this.settings.enabled = this.container.isVisible();
      this.saveSettings();
    }
  }
  // 供外部调用的方法
  getPets() {
    var _a;
    return ((_a = this.container) == null ? void 0 : _a.getPets()) || [];
  }
  createPet() {
    var _a;
    return (_a = this.container) == null ? void 0 : _a.createPet();
  }
};
var CatPetSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u{1F431} \u5BA0\u7269\u8BBE\u7F6E" });
    new import_obsidian4.Setting(containerEl).setName("\u542F\u7528\u5BA0\u7269").setDesc("\u663E\u793A/\u9690\u85CF\u6240\u6709\u5BA0\u7269").addToggle((toggle) => toggle.setValue(this.plugin.settings.enabled).onChange(async (value) => {
      this.plugin.settings.enabled = value;
      await this.plugin.saveSettings();
      if (value && !this.plugin.container) {
        this.plugin.container = new PetContainer(this.app, this.plugin);
        await this.plugin.loadPets();
      } else if (!value && this.plugin.container) {
        this.plugin.container.destroy();
        this.plugin.container = null;
      }
    }));
    new import_obsidian4.Setting(containerEl).setName("\u6700\u5927\u5BA0\u7269\u6570\u91CF").setDesc("\u9650\u5236\u540C\u65F6\u663E\u793A\u7684\u5BA0\u7269\u6570\u91CF").addSlider((slider) => slider.setLimits(1, 10, 1).setValue(this.plugin.settings.maxPets).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.maxPets = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian4.Setting(containerEl).setName("\u9ED8\u8BA4\u5BA0\u7269\u7C7B\u578B").setDesc("\u65B0\u5EFA\u5BA0\u7269\u65F6\u9ED8\u8BA4\u4F7F\u7528\u7684\u7C7B\u578B").addDropdown((dropdown) => {
      const options = getPetTypeOptions();
      options.forEach((opt) => dropdown.addOption(opt.value, opt.label));
      return dropdown.setValue(this.plugin.settings.defaultPetType).onChange(async (value) => {
        this.plugin.settings.defaultPetType = value;
        const typeConfig = getPetTypeConfig(value);
        if (typeConfig && typeConfig.variants.length > 0) {
          this.plugin.settings.defaultPetVariant = typeConfig.variants[0].id;
        }
        await this.plugin.saveSettings();
        this.display();
      });
    });
    new import_obsidian4.Setting(containerEl).setName("\u9ED8\u8BA4\u5BA0\u7269\u5916\u89C2").setDesc("\u65B0\u5EFA\u5BA0\u7269\u65F6\u9ED8\u8BA4\u4F7F\u7528\u7684\u5916\u89C2").addDropdown((dropdown) => {
      const options = getPetVariantOptions(this.plugin.settings.defaultPetType);
      options.forEach((opt) => dropdown.addOption(opt.value, opt.label));
      return dropdown.setValue(this.plugin.settings.defaultPetVariant).onChange(async (value) => {
        this.plugin.settings.defaultPetVariant = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian4.Setting(containerEl).setName("\u663E\u793A\u7EDF\u8BA1\u4FE1\u606F").setDesc("\u5728\u8BBE\u7F6E\u9762\u677F\u663E\u793A\u5F53\u524D\u5BA0\u7269\u5217\u8868").addToggle((toggle) => toggle.setValue(this.plugin.settings.showStats).onChange(async (value) => {
      this.plugin.settings.showStats = value;
      await this.plugin.saveSettings();
      this.display();
    }));
    containerEl.createEl("h3", { text: "\u4F7F\u7528\u8BF4\u660E" });
    const infoEl = containerEl.createEl("div", { cls: "setting-item-description" });
    infoEl.innerHTML = `
			<p>\u53F3\u952E\u70B9\u51FB\u5BA0\u7269\u53EF\u4EE5\uFF1A</p>
			<ul>
				<li>\u{1F4AC} <strong>\u5F00\u59CB\u5BF9\u8BDD</strong> - \u6253\u5F00\u804A\u5929\u6C14\u6CE1\u4E0E\u5BA0\u7269\u4E92\u52A8</li>
				<li>\u{1F4DD} <strong>\u8F6C\u5316\u4E3A\u5361\u7247</strong> - \u5C06\u5BF9\u8BDD\u4FDD\u5B58\u4E3A\u7B14\u8BB0</li>
				<li>\u270F\uFE0F <strong>\u6539\u540D</strong> - \u7ED9\u5BA0\u7269\u8D77\u65B0\u540D\u5B57</li>
			</ul>
			<p>\u5DE6\u952E\u70B9\u51FB\u5BA0\u7269\u53EF\u4EE5\u629A\u6478\u5B83 \u2764\uFE0F</p>
		`;
    containerEl.createEl("h3", { text: "\u53EF\u7528\u5BA0\u7269\u7C7B\u578B" });
    const typeList = containerEl.createEl("ul");
    PET_TYPES.forEach((type) => {
      const li = typeList.createEl("li");
      li.setText(`${type.name}: ${type.variants.length} \u79CD\u5916\u89C2`);
    });
    if (this.plugin.settings.showStats) {
      containerEl.createEl("h3", { text: "\u5F53\u524D\u5BA0\u7269" });
      const pets = this.plugin.getPets();
      if (pets.length === 0) {
        containerEl.createEl("p", { text: "\u8FD8\u6CA1\u6709\u5BA0\u7269\uFF0C\u4F7F\u7528\u547D\u4EE4\u300C\u65B0\u5EFA\u5BA0\u7269\u300D\u6765\u521B\u5EFA\u3002" });
      } else {
        const list = containerEl.createEl("ul");
        for (const pet of pets) {
          const item = list.createEl("li");
          item.setText(`${pet.name} (${getPetFullDescription(pet)}) - ${this.getStateText(pet.state.type)}`);
        }
      }
    }
  }
  getStateText(state) {
    const stateMap = {
      idle: "\u53D1\u5446\u4E2D",
      walk: "\u6563\u6B65\u4E2D",
      sleep: "\u7761\u89C9\u4E2D",
      petted: "\u88AB\u629A\u6478\u4E2D"
    };
    return stateMap[state] || "\u672A\u77E5\u72B6\u6001";
  }
};
